# Generated by Django 4.0.2 on 2022-03-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_woolen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Woolen',
        ),
    ]
